name: eco_cycle_cloud
description: "EcoCycleCloud's members app to encourage recycling."
publish_to: 'none'
version: 0.1.0
environment:
  sdk: '>=3.5.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sembast: ^3.7.5
  path: ^1.9.0
  path_provider: ^2.1.4
  google_fonts: ^6.2.1
  provider: ^6.1.2
  flutter_map: ^7.0.2
  geolocator: ^13.0.1
  meta: ^1.15.0
  intl: ^0.19.0
  font_awesome_flutter: ^10.7.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  uses-material-design: true
